apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: testinpixon
  description: An example of a Backstage application.
  # Example for optional annotations
  # annotations:
    # github.com/project-slug: backstage/backstage
    # backstage.io/techdocs-ref: url:https://github.com/backstage/backstage
spec:
  type: website
  owner: sweta@example.com
  lifecycle: experimental
