version: '3'
services:
  backstage-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: backstage-frontend
    container_name: backstage-frontend
    ports:
      - 3000:3000
    depends_on:
      - backstage-db
  backstage-db:
    build:
      context: .
      dockerfile: docker/db/Dockerfile
      args:
        - pdb=$POSTGRES_DB
        - puser=$POSTGRES_USER
        - ppass=$POSTGRES_PASSWORD
    image: backstage-db
    container_name: backstage-db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
  backstage-backend:
    build:
      context: .
      dockerfile: packages/backend/Dockerfile
      args:
        - phost=backstage-db
        - pdb=$POSTGRES_DB
        - puser=$POSTGRES_USER
        - ppass=$POSTGRES_PASSWORD
        - gh_token=$GITHUB_TOKEN
        - auth_okta_cid=$AUTH_OKTA_CLIENT_ID
        - auth_okta_cs=$AUTH_OKTA_CLIENT_SECRET
        - auth_okta_au=$AUTH_OKTA_AUDIENCE
        - auth_gh_cid=$AUTH_GITHUB_CLIENT_ID
        - auth_gh_cs=$AUTH_GITHUB_CLIENT_SECRET
    image: backstage-backend
    container_name: backstage-backend
    depends_on:
      - backstage-db
    ports:
      - '7000:7000'
volumes:
  postgres_data:
