apiVersion: v1
kind: Service
metadata:
  name: {{ include "backstage.fullname" . }}-frontend
spec:
  ports:
    - port: {{ .Values.frontend.containerPort }}
      targetPort: {{ .Values.frontend.containerPort }}

  selector:
    app: backstage
    component: frontend

  type: {{ .Values.frontend.serviceType }}