apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: "nginx"
  creationTimestamp: null
  name: {{ .Values.ingress.name }}
spec:
  tls:
    - secretName: echo-tls
      hosts:
        - {{ .Values.ingress.host }}
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ .Release.Namespace }}-frontend
              servicePort: {{ .Values.ingress.frontend.containerPort }}
          - path: /api
            backend:
              serviceName: {{ .Release.Namespace }}-backend
              servicePort: {{ .Values.ingress.backend.containerPort }}
status:
  loadBalancer: {}
