apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Namespace }}-backend
spec:
  ports:
    - port: {{ .Values.backend.containerPort }}
      targetPort: {{ .Values.backend.containerPort }}
  selector:
    app: backstage
    component: backend

  type: {{ .Values.backend.serviceType }}