apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: example-components
  description: A collection of all Backstage example components
spec:
  targets:
    - ./components/workplace-component.yaml
    - ./components/mapping-component.yaml
    - ./components/aware-component.yaml
    - ./components/analytics-component.yaml
    - ./components/maps-analytics-component.yaml
    - ./components/odp-analytics-component.yaml

