apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: example-components
  description: A collection of all Backstage example components
spec:
  targets:
    - ./components/workplace-component.yaml
    - ./components/jacs-component.yaml
    - ./components/asset-tracking-component.yaml  
