apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: analytics
  description: Analytics
  
spec:
  type: service
  lifecycle: production
  owner: inpixon
  providesApis:
    - analyticsapi
    
