apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: aware
  description: Aware
  
spec:
  type: service
  lifecycle: production
  owner: inpixon
  providesApis:
    - awareproducerservice
    - awarecoreinsight
