apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: odpanalytics
  desription: ODP Analytics
  
spec:
  type: service
  lifecycle: production
  owner: inpixon
  providesApis:
    - odpanalyticsapi
    
