# This is a basic workflow to help you get started with Actions

name: Pull & Merge Changes from upstream

# Controls when the workflow will run
on:
  schedule:
    - cron: "0 9 * * 1"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  merge:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Merge upstream
        env:
          GH_NAME: ${{ secrets.GH_NAME }}
          GH_EMAIL: ${{ secrets.GH_EMAIL }}
        run: |
          git config --global user.name '$GH_NAME'
          git config --global user.email '$GH_EMAIL'

          git pull --unshallow  # this option is very important, you would get
                                # complains about unrelated histories without it.
                                # (but actions/checkout@v2 can also be instructed
                                # to fetch all git depth right from the start)

          git remote add backstage https://github.com/backstage/backstage
          git fetch backstage

          git checkout ci_test
          git merge --no-edit backstage/master
      
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
